name: MegaTW_Master
main: com.andrewyunt.megatw_master.MegaTWMaster
version: 1.0
depend: [MegaTW_Base]

############################################################
# +------------------------------------------------------+ #
# |                      Permissions                     | #
# +------------------------------------------------------+ #
############################################################
permissions:
   megatw.*:
     description: Gives access to all MegaTW commands.
     children:
       megatw.arena: true
       megatw.createarena: true
       megatw.deletearena: true
       megatw.addspawn: true
       megatw.removespawn: true
